# Generated by Django 3.2.5 on 2021-07-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='City',
            new_name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default='dhaka', max_length=255),
            preserve_default=False,
        ),
    ]
